USE prints;
DROP TABLE IF EXISTS artists;
CREATE TABLE artists (
	id INT UNSIGNED AUTO_INCREMENT,
	familyname VARCHAR(40) DEFAULT NULL,
	givenname VARCHAR(40) DEFAULT NULL,
	aka VARCHAR(24) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE INDEX aka (aka)
) ENGINE=INNODB;
