USE prints;
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (
	id INT UNSIGNED AUTO_INCREMENT,
	customerid INT UNSIGNED NOT NULL,
	total DECIMAL(10,2) DEFAULT NULL,
	orderdate DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (customerid) REFERENCES users(id)
) ENGINE=INNODB;

DROP TABLE IF EXISTS orderitems;
CREATE TABLE orderitems (
	id INT UNSIGNED AUTO_INCREMENT,
	orderid INT UNSIGNED NOT NULL,
	printid INT UNSIGNED NOT NULL,
	quantity INT UNSIGNED NOT NULL DEFAULT 1,
	price DECIMAL(6,2) DEFAULT NULL,
	shipdate DATETIME DEFAULT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (orderid) REFERENCES orders(id),
	FOREIGN KEY (printid) REFERENCES prints(id)
) ENGINE=INNODB;
