USE prints;
DROP TABLE IF EXISTS prints;
CREATE TABLE prints (
	id INT UNSIGNED AUTO_INCREMENT,
	artistid INT UNSIGNED NOT NULL,
	title VARCHAR(60) NOT NULL,
	price DECIMAL(6,2), -- ie 0000.00
	size VARCHAR(24) DEFAULT NULL,
	description TEXT DEFAULT NULL,
	src VARCHAR(64) NOT NULL,
	filename VARCHAR(64) NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT artistid FOREIGN KEY (artistid) REFERENCES artists(id) ON DELETE RESTRICT ON UPDATE RESTRICT
		--  or RESTRICT | CASCADE | SET NULL | NO ACTION
) ENGINE=INNODB;
